### PR TITLE
Added webhooks.py

### PR DESCRIPTION
**Pull request by baryonyx5**
I've been working with pyCiscoSparkAPI over the last week or so.  I haven't found any issues except for a few typos here and there.  

I added a webhooks module following the conventions you used for the other modules.  I also added some tests.  I'd be happy to add additional tests if you're ok with the structure. 

Let me know if you have any questions or comments. 

Thanks

Change Log
Added tests for webhooks and rooms (using py.test)
Removed duplicate **init** method in rooms.py
Fixed method name (createMemebershipToRoomByPersonId) in memberships.py
Fixed key name in multiple methods (pesonEmail) in messages.py
Converted attribute methods to properies in Room, Person, Membership
Added debug attribute to SparkClient to enable debugging
Various PEP8-related formatting updates

### CODE REVIEW

**Comment by shenning00** [comment]
Thanks for the contribution. I will merge this in tomorrow.

**Comment by shenning00** [comment]
Thanks for the updates. Looks like I had made the same fixes you had since all I saw was the new webhooks and test code you added. Looks good.

**Comment by shenning00** [comment]
Looks like a I missed something. I don't see the changes for the 'debug' option.

**Comment by baryonyx5** [comment]
Crap, for some reason, none of my modifications to existing files were committed.  I'll create a new pull request for these.  

Sorry about that

**Pull request merged**
